logging:
  level:
    org.togglz: DEBUG
togglz:
  features:
    HELLO_WORLD:
      enabled: true
    REVERSE_GREETING:
      enabled: false
  console:
    secured: false
management:
  endpoints:
    web:
      exposure:
        include: '*'